services:
  dbspigot:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DBSPIGOT_USER=admin
      - DBSPIGOT_PASS=changeme
      - DBSPIGOT_HOST=localhost
    restart: unless-stopped
